source = ~/.config/hypr/conf/keybindings/default.conf

# Application
unbind = $mainMod, S
unbind = $mainMod, M
unbind = $mainMod, D
unbind = CTRL SHIFT, escape 

bind = $mainMod, S, exec, steam                                       # Open Steam 
bind = $mainMod, M, exec, flatpak run com.github.iwalton3.jellyfin-media-player # Open Jellyfin
bind = $mainMod, D, exec, flatpak run dev.vencord.Vesktop # Open Discord
bind = CTRL SHIFT, escape, exec, $(cat ~/.config/ml4w/settings/terminal.sh) --class dotfiles-floating -e btop  # Open btop

# Windows
unbind = $mainMod SHIFT, M

bind = $mainMod SHIFT, M, fullscreen, 1                                                           # Maximize Window

# Actions
unbind = $mainMod, escape
unbind = $mainMod, space

bind = $mainMod, escape, exec, ~/.config/ml4w/scripts/wlogout.sh                          # Start wlogout
bind = $mainMod, space, exec, ~/.config/hypr/scripts/launcher.sh                    # Open application launcher

# Sidepad
unbind = $mainMod SHIFT CTRL, S

bind = $mainMod SHIFT CTRL, S, exec, ~/.config/ml4w/scripts/sidepad.sh --init                        # Init Sidepad

# Workspaces
unbind = $mainMod CTRL, 1
unbind = $mainMod CTRL, 2
unbind = $mainMod CTRL, 3
unbind = $mainMod CTRL, 4
unbind = $mainMod CTRL, 5
unbind = $mainMod CTRL, 6
unbind = $mainMod CTRL, 7
unbind = $mainMod CTRL, 8
unbind = $mainMod CTRL, 9
unbind = $mainMod CTRL, 0

bind = $mainMod CTRL, 1, movetoworkspace, 1  # Move active window to workspace 1
bind = $mainMod CTRL, 2, movetoworkspace, 2  # Move active window to workspace 2
bind = $mainMod CTRL, 3, movetoworkspace, 3  # Move active window to workspace 3
bind = $mainMod CTRL, 4, movetoworkspace, 4  # Move active window to workspace 4
bind = $mainMod CTRL, 5, movetoworkspace, 5  # Move active window to workspace 5
bind = $mainMod CTRL, 6, movetoworkspace, 6  # Move active window to workspace 6
bind = $mainMod CTRL, 7, movetoworkspace, 7  # Move active window to workspace 7
bind = $mainMod CTRL, 8, movetoworkspace, 8  # Move active window to workspace 8
bind = $mainMod CTRL, 9, movetoworkspace, 9  # Move active window to workspace 9
bind = $mainMod CTRL, 0, movetoworkspace, 10 # Move active window to workspace 10

unbind = $mainMod SHIFT, 1
unbind = $mainMod SHIFT, 2
unbind = $mainMod SHIFT, 3
unbind = $mainMod SHIFT, 4
unbind = $mainMod SHIFT, 5
unbind = $mainMod SHIFT, 6
unbind = $mainMod SHIFT, 7
unbind = $mainMod SHIFT, 8
unbind = $mainMod SHIFT, 9
unbind = $mainMod SHIFT, 0

bind = $mainMod SHIFT, 1, exec, $HYPRSCRIPTS/moveTo.sh 1  # Move all windows to workspace 1
bind = $mainMod SHIFT, 2, exec, $HYPRSCRIPTS/moveTo.sh 2  # Move all windows to workspace 2
bind = $mainMod SHIFT, 3, exec, $HYPRSCRIPTS/moveTo.sh 3  # Move all windows to workspace 3
bind = $mainMod SHIFT, 4, exec, $HYPRSCRIPTS/moveTo.sh 4  # Move all windows to workspace 4
bind = $mainMod SHIFT, 5, exec, $HYPRSCRIPTS/moveTo.sh 5  # Move all windows to workspace 5
bind = $mainMod SHIFT, 6, exec, $HYPRSCRIPTS/moveTo.sh 6  # Move all windows to workspace 6
bind = $mainMod SHIFT, 7, exec, $HYPRSCRIPTS/moveTo.sh 7  # Move all windows to workspace 7
bind = $mainMod SHIFT, 8, exec, $HYPRSCRIPTS/moveTo.sh 8  # Move all windows to workspace 8
bind = $mainMod SHIFT, 9, exec, $HYPRSCRIPTS/moveTo.sh 9  # Move all windows to workspace 9
bind = $mainMod SHIFT, 0, exec, $HYPRSCRIPTS/moveTo.sh 10 # Move all windows to workspace 10
